// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: Products.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Products_GetProduct_FullMethodName             = "/rpc.Products/GetProduct"
	Products_GetProducts_FullMethodName            = "/rpc.Products/GetProducts"
	Products_CreateProducts_FullMethodName         = "/rpc.Products/CreateProducts"
	Products_CreateProductsInStream_FullMethodName = "/rpc.Products/CreateProductsInStream"
)

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsClient interface {
	// Demonstrates a request response call
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
	// Demonstrates a server streamer call
	GetProducts(ctx context.Context, in *GetProductsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Product], error)
	// Demonstrates a client streaming call
	CreateProducts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Product, CreateProductsResp], error)
	// Demonstrates a bidirectional streaming call
	CreateProductsInStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Product, Product], error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResp)
	err := c.cc.Invoke(ctx, Products_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetProducts(ctx context.Context, in *GetProductsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Product], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Products_ServiceDesc.Streams[0], Products_GetProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetProductsReq, Product]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_GetProductsClient = grpc.ServerStreamingClient[Product]

func (c *productsClient) CreateProducts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Product, CreateProductsResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Products_ServiceDesc.Streams[1], Products_CreateProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Product, CreateProductsResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_CreateProductsClient = grpc.ClientStreamingClient[Product, CreateProductsResp]

func (c *productsClient) CreateProductsInStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Product, Product], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Products_ServiceDesc.Streams[2], Products_CreateProductsInStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Product, Product]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_CreateProductsInStreamClient = grpc.BidiStreamingClient[Product, Product]

// ProductsServer is the server API for Products service.
// All implementations must embed UnimplementedProductsServer
// for forward compatibility.
type ProductsServer interface {
	// Demonstrates a request response call
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
	// Demonstrates a server streamer call
	GetProducts(*GetProductsReq, grpc.ServerStreamingServer[Product]) error
	// Demonstrates a client streaming call
	CreateProducts(grpc.ClientStreamingServer[Product, CreateProductsResp]) error
	// Demonstrates a bidirectional streaming call
	CreateProductsInStream(grpc.BidiStreamingServer[Product, Product]) error
	mustEmbedUnimplementedProductsServer()
}

// UnimplementedProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductsServer struct{}

func (UnimplementedProductsServer) GetProduct(context.Context, *GetProductReq) (*GetProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductsServer) GetProducts(*GetProductsReq, grpc.ServerStreamingServer[Product]) error {
	return status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedProductsServer) CreateProducts(grpc.ClientStreamingServer[Product, CreateProductsResp]) error {
	return status.Errorf(codes.Unimplemented, "method CreateProducts not implemented")
}
func (UnimplementedProductsServer) CreateProductsInStream(grpc.BidiStreamingServer[Product, Product]) error {
	return status.Errorf(codes.Unimplemented, "method CreateProductsInStream not implemented")
}
func (UnimplementedProductsServer) mustEmbedUnimplementedProductsServer() {}
func (UnimplementedProductsServer) testEmbeddedByValue()                  {}

// UnsafeProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServer will
// result in compilation errors.
type UnsafeProductsServer interface {
	mustEmbedUnimplementedProductsServer()
}

func RegisterProductsServer(s grpc.ServiceRegistrar, srv ProductsServer) {
	// If the following call pancis, it indicates UnimplementedProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Products_ServiceDesc, srv)
}

func _Products_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProductsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductsServer).GetProducts(m, &grpc.GenericServerStream[GetProductsReq, Product]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_GetProductsServer = grpc.ServerStreamingServer[Product]

func _Products_CreateProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).CreateProducts(&grpc.GenericServerStream[Product, CreateProductsResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_CreateProductsServer = grpc.ClientStreamingServer[Product, CreateProductsResp]

func _Products_CreateProductsInStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductsServer).CreateProductsInStream(&grpc.GenericServerStream[Product, Product]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Products_CreateProductsInStreamServer = grpc.BidiStreamingServer[Product, Product]

// Products_ServiceDesc is the grpc.ServiceDesc for Products service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Products_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _Products_GetProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetProducts",
			Handler:       _Products_GetProducts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateProducts",
			Handler:       _Products_CreateProducts_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateProductsInStream",
			Handler:       _Products_CreateProductsInStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Products.proto",
}
