// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: Products.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_Products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_Products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_Products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReq) Reset() {
	*x = GetProductsReq{}
	mi := &file_Products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReq) ProtoMessage() {}

func (x *GetProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReq.ProtoReflect.Descriptor instead.
func (*GetProductsReq) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetProductsReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsResp) Reset() {
	*x = CreateProductsResp{}
	mi := &file_Products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsResp) ProtoMessage() {}

func (x *CreateProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsResp.ProtoReflect.Descriptor instead.
func (*CreateProductsResp) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_Products_proto protoreflect.FileDescriptor

const file_Products_proto_rawDesc = "" +
	"\n" +
	"\x0eProducts.proto\x12\x03rpc\"C\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"8\n" +
	"\x0eGetProductResp\x12&\n" +
	"\aproduct\x18\x01 \x01(\v2\f.rpc.ProductR\aproduct\">\n" +
	"\x0eGetProductsReq\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\">\n" +
	"\x12CreateProductsResp\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.rpc.ProductR\bproducts2\xf2\x01\n" +
	"\bProducts\x127\n" +
	"\n" +
	"GetProduct\x12\x12.rpc.GetProductReq\x1a\x13.rpc.GetProductResp\"\x00\x124\n" +
	"\vGetProducts\x12\x13.rpc.GetProductsReq\x1a\f.rpc.Product\"\x000\x01\x12;\n" +
	"\x0eCreateProducts\x12\f.rpc.Product\x1a\x17.rpc.CreateProductsResp\"\x00(\x01\x12:\n" +
	"\x16CreateProductsInStream\x12\f.rpc.Product\x1a\f.rpc.Product\"\x00(\x010\x01B5Z-github.com/didirdt/router-template/protos/rpc\xea\x02\x03rpcb\x06proto3"

var (
	file_Products_proto_rawDescOnce sync.Once
	file_Products_proto_rawDescData []byte
)

func file_Products_proto_rawDescGZIP() []byte {
	file_Products_proto_rawDescOnce.Do(func() {
		file_Products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Products_proto_rawDesc), len(file_Products_proto_rawDesc)))
	})
	return file_Products_proto_rawDescData
}

var file_Products_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Products_proto_goTypes = []any{
	(*Product)(nil),            // 0: rpc.Product
	(*GetProductReq)(nil),      // 1: rpc.GetProductReq
	(*GetProductResp)(nil),     // 2: rpc.GetProductResp
	(*GetProductsReq)(nil),     // 3: rpc.GetProductsReq
	(*CreateProductsResp)(nil), // 4: rpc.CreateProductsResp
}
var file_Products_proto_depIdxs = []int32{
	0, // 0: rpc.GetProductResp.product:type_name -> rpc.Product
	0, // 1: rpc.CreateProductsResp.products:type_name -> rpc.Product
	1, // 2: rpc.Products.GetProduct:input_type -> rpc.GetProductReq
	3, // 3: rpc.Products.GetProducts:input_type -> rpc.GetProductsReq
	0, // 4: rpc.Products.CreateProducts:input_type -> rpc.Product
	0, // 5: rpc.Products.CreateProductsInStream:input_type -> rpc.Product
	2, // 6: rpc.Products.GetProduct:output_type -> rpc.GetProductResp
	0, // 7: rpc.Products.GetProducts:output_type -> rpc.Product
	4, // 8: rpc.Products.CreateProducts:output_type -> rpc.CreateProductsResp
	0, // 9: rpc.Products.CreateProductsInStream:output_type -> rpc.Product
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Products_proto_init() }
func file_Products_proto_init() {
	if File_Products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Products_proto_rawDesc), len(file_Products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Products_proto_goTypes,
		DependencyIndexes: file_Products_proto_depIdxs,
		MessageInfos:      file_Products_proto_msgTypes,
	}.Build()
	File_Products_proto = out.File
	file_Products_proto_goTypes = nil
	file_Products_proto_depIdxs = nil
}
